export const W = 800
export const H = 600
export const PLAYER_W = 48
export const PLAYER_H = 24
export const PLAYER_SPEED = 4
export const BULLET_W = 4
export const BULLET_H = 12
export const PLAYER_BULLET_SPEED = 7
export const ALIEN_BULLET_SPEED = 3
export const ALIEN_COLS = 11
export const ALIEN_ROWS = 5
export const ALIEN_W = 36
export const ALIEN_H = 28
export const ALIEN_PAD_X = 16
export const ALIEN_PAD_Y = 14
export const ALIEN_STEP = 10          // pixels moved each step
export const ALIEN_STEP_INTERVAL = 600 // ms between steps (speeds up over time)
export const ALIEN_DROP = 16           // pixels dropped when hitting wall
export const UFO_W = 48
export const UFO_H = 22
export const UFO_SPEED = 2
export const UFO_INTERVAL = 25000     // ms between UFO appearances
export const SHIELD_COUNT = 4
export const MAX_LIVES = 3
export const ALIEN_FIRE_INTERVAL = 1200 // ms between alien shots
export const POWER_UP_SPEED = 2
export const POWER_UP_DROP_CHANCE = 0.15
export const POWER_UP_SIZE = 16
export const POWER_UP_DURATION = 8000  // ms effect duration
export const BASE_SHOOT_COOLDOWN = 400
export const RAPID_SHOOT_COOLDOWN = 150
export const PLAYER_HIT_DURATION = 2000
